### ISSUE TITLE
Plain HTML is lost when a composite component is added dynamically and is re-rendered

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#3767]
A problem similar to the one described in issue 3158.

A composite component which contains a mixture of plain HTML and JSF tags is added dynamically with FaceletContext.
If the partial response is rendered first, everything is fine.
But if another AJAX request is submitted and the part of the HTML document which contains the composite is updated,
the plain HTML is missing.

I will provide an example where the initial view already contains an instance of the Composite (dcc:foo).
There is a button for adding another instance of the foo component.
Afterwards, if one Triggers the other button 'Partial update', the updated page obviously does not look alright.

I am well aware that issue 3158 has been closed 'working as designed' and that you couldn't reproduce that error.

Note that I am using Tomcat (instead of Glassfish), as well, just as the reporter of 3158.
But I guess, there shoudn't be any difference just because of different Container implementations.
#### Environment
Tomcat 7.0.47
#### Affected Versions
[2.2.10]

**Comment by ruolli** [comment]
The fact is that, the HTML was already lost during the state restore process,
but, the lost happened in state save process before the next state restore process.

Each time, the dynamic component, which contains HTML and JSF tags, is created, it was added to <body> in the last, and is shown correctly.

But, when state save happens, the HTML was lost in FaceletPartialStateManagementStrategy::saveState(),
because HTML content was parsed to UIInstructions, whose isTransient() returns true.
Thus, not saved in state save process.

However, modifying the isTransient() of UIInstructions is not suitable, neither is it possible.
The reason is that, UIInstructions is the sub-class of UILeaf, both of which have no default constructor.
For the objects saved/restored in/from the state, its class must have a default constructor, for instances, UIOutput, HtmlBody, etc.

So, my understanding now is that, the UIInstructions objects are not expected to be saved at all.
In order to save the HTML content to state, we need to modify the compiler, which compiles XML/HTML pages.

If that's the case, the modification to fix this issue would not be a trivial one, or, we should not do the modification at all.

**Comment by ruolli** [comment]
===========
com.sun.faces.application.view.FaceletPartialStateManagementStrategy: 

    public Object saveView(FacesContext context) {
        if (LOGGER.isLoggable(Level.FINEST)) {
            LOGGER.finest("FaceletPartialStateManagementStrategy.saveView");
        }

        if (context == null) {
            return null;
        }

        UIViewRoot viewRoot = context.getViewRoot();
        if (viewRoot.isTransient()) {
            return null;
        }

        Util.checkIdUniqueness(context, viewRoot, new HashSet<String>(viewRoot.getChildCount() << 1));

        final Map<String, Object> stateMap = new HashMap<String, Object>();
        final StateContext stateContext = StateContext.getStateContext(context);

        context.getAttributes().put(SKIP_ITERATION_HINT, true);
        Set<VisitHint> hints = EnumSet.of(VisitHint.SKIP_ITERATION);
        VisitContext visitContext = VisitContext.createVisitContext(context, null, hints);
        final FacesContext finalContext = context;

        try {
            viewRoot.visitTree(visitContext, new VisitCallback() {

                public VisitResult visit(VisitContext context, UIComponent target) {
                    VisitResult result = VisitResult.ACCEPT;
                    Object stateObj;
                    if (!target.isTransient()) {
                        if (stateContext.componentAddedDynamically(target)) {
                            target.getAttributes().put(DYNAMIC_COMPONENT, target.getParent().getChildren().indexOf(target));
                            stateObj = new StateHolderSaver(finalContext, target);
                        } else {
                            stateObj = target.saveState(context.getFacesContext());
                        }
                        if (stateObj != null) {
                            stateMap.put(target.getClientId(context.getFacesContext()), stateObj);
                        }
                    } else {
                        return VisitResult.REJECT;
                    }
                    return result;
                }
            });
        } finally {
            context.getAttributes().remove(SKIP_ITERATION_HINT);
        }

        saveDynamicActions(context, stateContext, stateMap);
        StateContext.release(context);
        return new Object[]{null, stateMap};
    }
}

===========

**Comment by ruolli** [comment]
Zhijun and I reviewed the scenario carefully.

The HTML tags were parsed by SAXCompiler to UIInstructions was the correct behavior.
The UIInstructions were designed not to be saved/restored.

So, in conclusion, JSF does not support the scenario for now.
The workaround would be using tags like <h:outputText> to wrap the HTML content.
