### ISSUE TITLE
useBundledJsf does not work completely: causes Target Unreachable, identifier … resolved to null

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4186]
Not sure whether this is to be considered a Glassfish issue or a JSF issue.

There is a complete description and mini web test app at:

*   [https://github.com/webelcomau/PrimeFaces_dataTable_JSF23/wiki](https://github.com/webelcomau/PrimeFaces_dataTable_JSF23/wiki)
*   [https://github.com/webelcomau/PrimeFaces_dataTable_JSF23/archive/master.zip](https://github.com/webelcomau/PrimeFaces_dataTable_JSF23/archive/master.zip)

That test web app works fine when I use the built-in Mojarra in Glassfish 4.1.1 OR when I use Mojarra 2.2.8-18 as .../glassfish/modules/javax.faces.jar.

(It fails for other reasons when I use Mojarra 2.3.0-m6 with a Primefaces 6.0 p:dataTable, but the problem reported here also occurs in any case when it is used as an app-specific JSF bundle.)

I am using the mini test web app to compare and test some JSF versions and rather than tediously copying various Mojarra implementation jars over the glassfish/modules I am using this in glassfish-web.xml:

```
<property name="useBundledJsf" value="true" />
<class-loader delegate="false" />
```

Between runs I use the NetBeans library jar manager to choose a JSF Mojarra version to test from a ./lib subfolder. When I use an application-specific Mojarra it is not resolving this:

```
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class ViewBean implements Serializable {
```
```
<f:event type="preRenderView" listener="#{viewBean.reset}"/>
```

Gives error (but only when app-specific useBundledJsf used):

```
Target Unreachable, identifier 'viewBean' resolved to null
```

I know that useBundledJsf is basically working at least partially because I have this in an index.xhtml landing page (before navigating to a page that uses the view scoped bean), and it echoes the application-specific Mojarra jar version fine:

```
#{facesContext.class.package.implementationTitle}: #{facesContext.class.package.implementationVersion}
```

**Q: Did JSF or Glassfish officially abandon support for 'useBundledJsf', and can somebody please shed some light on how to (now) use an application-specific Mojarra jar easily (so I can swap them in and out without impacting on other webapps) ?**

I did not find the explanation I seek searching on the Glassfish or JSF JIRA.

On the Payara GitHub issues I found this: [useBundledJSF flag makes ServletContainerInitializer get an empty class set and breaks Mojarra 2.2.11 and up #170](https://github.com/payara/Payara/issues/710), where it reports:

> We tried updating our Mojarra version in our application from 2.2.10 to 2.2.12\. I was surprised that the application did not work anymore after the update.
> 
> Digging a little deeper into the code it seems that from Mojarra version 2.2.11 ![](https://java.net/jira/images/icons/emoticons/add.gif) the Mojarra library does not handle the annotation scanning by itself anymore but relies on the container to provide the classes which contain annotations. When the flag "useBundledJSF" in glassfish-web.xml is set to true, the set of classes is empty and this has the effect that no annotated bean can be found.

It seems I am experiencing something similar.

_Possibly related: [JAVASERVERFACES-3957 @FacesComponent is not detected when using JSF with Spring Boot](https://java.net/jira/browse/JAVASERVERFACES-3957)_
#### Environment
Mac OS X 10.10.5
NetBeans8.1
GlassFish 4.1.1
#### Affected Versions
[2.2.8-12, 2.2.8-18, 2.3.0-m06]

**Comment by ruolli** [comment]
After debugging the behavior of JSF 2.2.11 and GF 4.1.1, I can draw the conclusion that this issue was caused by GlassFish . 

The upgrade of JSF 2.2.10 to 2.2.11 is merely the trigger of the potential problem inside GF .
In 2.2.10 and pre-2.2.10 JSF versions, com.sun.faces.config.DelegatingAnnotationProvider::getAnnotatedClasses(Set<URI> urls) was like below, depending on com.sun.faces.config.JavaClassScanningAnnotationScanner to scan and return annotated classes. 
==================
    @Override
    public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls) {
        if (null == scanner) {
            scanner = new JavaClassScanningAnnotationScanner(sc);
        }   
        return scanner.getAnnotatedClasses(urls);
    }   
===================

From 2.2.11 on, JSF depends on Container to return annotated classes. 
===================
    @Override
    public Map<Class<? extends Annotation>, Set<Class<?>>> getAnnotatedClasses(Set<URI> urls) {
        HashMap<Class<? extends Annotation>, Set<Class<?>>> annotatedMap = new HashMap<Class<? extends Annotation>, Set<Class<?>>>();
        createAnnotatedMap(annotatedMap, (Set<Class<?>>) sc.getAttribute(ANNOTATED_CLASSES));
        return annotatedMap;
    }
===================

So, web container is expected to scan the annotated classes and put them into ServletContext to return by "sc.getAttribute(ANNOTATED_CLASSES)" .

Debugging the behavior of GF, in com.sun.enterprise.web.WebModule.java::configureMiscSettings() , if "useBundledJsf" is configured in glassfish-web.xml, setUseMyFaces() would be invoked. 
==============
                } else if("useMyFaces".equalsIgnoreCase(name)) {
                    setUseMyFaces(ConfigBeansUtilities.toBoolean(value));
                } else if("useBundledJsf".equalsIgnoreCase(name)) {
                    setUseMyFaces(ConfigBeansUtilities.toBoolean(value));
==============

Then, when org.apache.catalina.core.StandardContext::callServletContainerInitializers() is invoked,  "isUseMyFaces() && Globals.FACES_INITIALIZER.equals(initializer.getName())" would cause the FacesInitializer.onStartup() not executed at all. 

===============
            for (Map.Entry<Class<? extends ServletContainerInitializer>, Set<Class<?>>> e :
                    initializerList.entrySet()) {
                Class<? extends ServletContainerInitializer> initializer = e.getKey();
                // See IT 11333
                if (isUseMyFaces() &&
                        Globals.FACES_INITIALIZER.equals(initializer.getName())) {
                    continue;
                }
                try {
                    if (log.isLoggable(Level.FINE)) {
                        log.log(Level.FINE, "Calling ServletContainerInitializer [" + initializer
                                + "] onStartup with classes " + e.getValue());
                    }
                    ServletContainerInitializer iniInstance =
                        initializer.newInstance();
                    iniInstance.onStartup(
                        initializerList.get(initializer), ctxt);
                } catch (Throwable t) {
                    String msg = MessageFormat.format(rb.getString(INVOKING_SERVLET_CONTAINER_INIT_EXCEPTION),
                                                      initializer.getCanonicalName());
                    log.log(Level.SEVERE, msg, t);
                    throw new LifecycleException(t);
                }
            }

===============

To solve the issue, GF perhaps could modify com.sun.enterprise.web.WebModule.java::configureMiscSettings(), not invoke "setUseMyFaces(ConfigBeansUtilities.toBoolean(value));" when "useBundledJsf" is configured. 

BTW, in GF, "useMyFaces" and "useBundledJsf" are seemingly interchangeable. Both are about using the *.jar inside the web applications to override the default *.jar delivered by GF. 
But, they are now sharing one variable "useMyFaces" in org.apache.catalina.core.StandardContext and in org.glassfish.web.loader.WebappClassLoader , causing the issue we are seeing .

**Comment by ruolli** [comment]
Besides, I'd like to paste several links here, which are all about this issue: 
https://github.com/payara/Payara/issues/710
https://github.com/javaserverfaces/mojarra/issues/3961
https://www.beyondjava.net/blog/updating-to-mojarra-2-2-11-may-break-your-spring-boot-application/
https://github.com/spring-projects/spring-boot/issues/3216

**Comment by ruolli** [comment]
The change of JSF Mojarra from JavaClassScanningAnnotationScanner.getAnnotatedClasses() to sc.getAttribute(ANNOTATED_CLASSES) happened in GIT commit 39ef9185ea .
